### PR TITLE
Add systemd unit template.

### PR DESCRIPTION
**Pull request by luismanson**
Hello, are you open to PRs?

### CODE REVIEW

**Comment by kanniget** [comment]
Thanks for that  ;-)

**Comment by luismanson** [comment]
You're welcome! Just one question, can I have more than one beacon defined?

**Comment by kanniget** [comment]
Not sure What you mean by Beacon?

**Comment by luismanson** [comment]
> Not sure What you mean by Beacon?

I meant lighthouse. Sorry

**Comment by kanniget** [comment]
Ok, I had not considered multiple lighthouses in this but it could be adjusted to cater for it. I will look at it.

Anything like that, if you raise an Issue I will track it from there.

**Comment by kanniget** [comment]
I modified the code around the lighthouses to support multiple, I dont have multiple so if you could test it I would appreciate it.

**Comment by luismanson** [comment]
Just got another VM on a free tier for this.. Thanks!

**Pull request merged**
